### ISSUE TITLE
Integration into FlashDevelop throws an error

### ISSUE THREAD

**Issue by ghost** [airext/native-mouse#2]
I'm using:
Air 3.9
FlashDevelop 4.5.2.5
Windows 7 x64

I've added the NativeMouseLib/bin/NativeMouseLib.swc to my Library.

In the Readme are two different democodes:

``` AS3
//Trace Hello
if (NativeMouse.isSupported){
    trace("Hello");
}

//Doesnt trace Hello
if (NativeMouse.isSupported()){
    trace("Hello");
}
```

Do I use isSupported() or isSupported? I could not find isSupported in NativeMouse.as.
But when I'm using isSupported(), he never gives back a true on Win7 x64. either in the IDE Debug-Mode or packaged as an *.air.

When I just get rid of the isSupported-Part and just write:

``` AS3
var info:Object = new NativeMouse().getMouseInfo();
```

The Code crashes with the following error:

``` AS3
[Fault] exception, information=TypeError: Error #1009: Cannot access a property or method of a null object reference.
```

So I guess NativeMouse really is not supported on my Win7?
I want to get the current Mouse Position on NATIVE_MOUSE_MOVE, to track where the window was dragged. Any Idea how to solve this?

**Comment by rozd** [comment]
Hi, MortimerNeuss!

You should use NativeMouse.isSupported() to check if NativeMouse is supported. I will fix readme file.

It seems that NativeMouse is not supported for your environment, but it should be. I'll try to reproduce this issue.

Thanks!

**Comment by rozd** [comment]
It seems problem is that you use .SWC instead of .ANE file. So try to link NativeMouse.ane with your project. I didn't actually use FlashDevelop, but found tutorial how to do this, hope it helps.

http://fermmm.wordpress.com/2014/01/04/working-tutorial-to-install-air-native-extensions-in-flash-develop-4-windows-desktop-project/

**Comment by ghost** [comment]
I've added the .ANE to the Library, but this didnt solved the problem. I also tried to just add the NativeMouseLib/src/org folder to my lib-path, as I was thinking the raw *.as Files at lest should work if not the fancy SWC/ANE, but it was the same result.

I've tried it inside the FlashDevelop IDE and with the exported and installed *.air without luck. I might leave it in there as it does not throw me an error, so I can test it the next days on other machines. Might be a problem with (my) Win7.

Thank you for getting back to this.

**Comment by rozd** [comment]
You can't use AS3 code directly from .as files, they only call functions implemented in .dll file. 

I suppose problem is in setup native extension in FlashDevelop. As I can see from the tutorial it is not easy to setup native extension in FlashDevelop at all. Did you pass all of these 10 steps from the tutorial?
